BirdCounter/Models/Bird.cs
using System.ComponentModel.DataAnnotations;

namespace BirdCounter.Models
{
    public class Bird
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

BirdCounter/Models/BirdCount.cs
namespace BirdCounter.Models
{
    public class BirdCount
    {
        public int Id { get; set; }
        public int BirdId { get; set; }
        public int SessionId { get; set; }
        public int Count { get; set; }
    }
}

BirdCounter/Models/BirdSession.cs
namespace BirdCounter.Models
{
    public class BirdSession
    {
        public Bird bird { get; set; }
        public BirdCount count { get; set; }
    }
}

BirdCounter/Models/DetailObject.cs
using System.Collections.Generic;

namespace BirdCounter.Models
{
    public class DetailObject
    {
        public Session session { get; set; }
        public List<BirdSession> birds { get; set; }
    }
}

BirdCounter/Models/ErrorViewModel.cs
using System;

namespace BirdCounter.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BirdCounter/Models/Session.cs
using System;

namespace BirdCounter.Models
{
    public class Session
    {
        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
}

BirdCounter/Controllers/BirdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BirdCounter.Data;
using BirdCounter.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace BirdCounter.Controllers
{
    public class BirdController : Controller
    {
        private DataBase DataBase { get; set; }

        private List<Bird> _birds { get; set; }
        
        public BirdController(DataBase database)
        {
            DataBase = database;
            _birds = DataBase.Birds.ToList();
        }

        public IActionResult Index()
        {
            return View(this);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Bird bird)
        {
            if (!ModelState.IsValid)
            {
                return View(bird);
            }

            DataBase.Birds.Add(bird);
            DataBase.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Remove(int birdId)
        {
            Bird bird = DataBase.Birds.FirstOrDefault(a => a.Id == birdId);
            if (bird != null)
            {
                DataBase.Birds.Remove(bird);
                DataBase.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int birdId)
        {
            var bird = DataBase.GetBirdById(birdId);
            return View(bird);
        }

        [HttpPost]
        public IActionResult Edit(Bird bird)
        {
            var dbBird = DataBase.Birds.FirstOrDefault(a => a.Id == bird.Id);
            if (!ModelState.IsValid)
            {
                return View(bird);
            }

            dbBird.Name = bird.Name;
            dbBird.Description = bird.Description;
            dbBird.Image = bird.Image;
            DataBase.SaveChanges();

            return RedirectToAction("Index");
        }

        public List<Bird> Birds => _birds;
    }
}

BirdCounter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BirdCounter.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BirdCounter.Models;
using BirdCounter.Views.Home;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.EntityFrameworkCore.Storage;

namespace BirdCounter.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private DataBase DataBase { get; set; }
        private List<Bird> _birds { get; set; }
        private List<Session> _sessions { get; set; }
        
        private DetailObject _currentCount { get; set; }

        public HomeController(ILogger<HomeController> logger, DataBase database)
        {
            _logger = logger;
            DataBase = database;
            
            _birds = new List<Bird>();
            _birds.AddRange(DataBase.getBirds());
            _sessions = new List<Session>();
            _sessions.AddRange(DataBase.getSessions());
        }

        public IActionResult Index()
        {
            return View(this);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Count(int SessionId = 0)
        {
            if (SessionId != 0)
            {
                _currentCount = DataBase.CreateDetailObject(SessionId);
            }
            else
            {
                _currentCount = DataBase.CreateDetailObject(DataBase.CreateSession());
            }
            
            return View(this);
        }

        public IActionResult Detail(int id)
        {
            DetailObject detail = DataBase.CreateDetailObject(id);
            return View(detail);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        public IActionResult AddCount(int sessionId, int BirdId)
        {
            DataBase.AddCount(BirdId, sessionId);
            return RedirectToAction("Count" ,new{SessionId = sessionId});
        }

        public IActionResult SubtractCount(int sessionId, int birdId)
        {
            DataBase.SubtractCount(birdId, sessionId);
            return RedirectToAction("Count", new{SessionId = sessionId});
        }

        public IActionResult EndSession(int id)
        {
            DataBase.EndSession(id);
            return RedirectToAction("Index");
        }
        public List<Bird> Birds
        {
            get
            {
                return _birds;
            }
            set
            {
                _birds = value;
            }
        }

        public List<Session> Sessions => _sessions;

        public DetailObject CurrentCount
        {
            get
            {
                return _currentCount;
            }
            set => _currentCount = value;
        }
    }
}

BirdCounter/Views/Bird/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

<h1>Add new bird</h1>
<form method="post">
    <partial name="CreateEditPartial" model="Model"/>
    <input type="submit" class="btn btn-primary" value="Create">
</form>

BirdCounter/Views/Bird/BirdPartial.cshtml
@model BirdCounter.Models.Bird;

<div class="card" >
    <img class="card-img-top" src="@Url.Content(Model.Image)" alt="Card image cap" runat="server">
    <div class="card-body">
        <h2 class="card-title">@Model.Name</h2>
        <p class="card-text">@Model.Description</p>
        <div class="card__actions__wrapper">
            <a asp-action="Edit" asp-route-birdId="@Model.Id" class="btn-primary card__action">Edit bird</a>
            <a asp-action="Remove" asp-route-birdId="@Model.Id" class="btn-danger card__action">Remove bird</a>
        </div>
    </div>
</div>

BirdCounter/Views/Bird/CreateEditPartial.cshtml
@model Bird

<div class="form-group">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name"></span>
</div>
<div class="form-group">
    <label asp-for="Description"></label>
    <input asp-for="Description" class="form-control"/>
    <span asp-validation-for="Description"></span>
</div>
<div class="form-group">
    <label asp-for="Image"></label>
    <input asp-for="Image" class="form-control" />
    <span asp-validation-for="Image"></span>
</div>
<input type="hidden" asp-for="Id" value="@Model.Id"/>

BirdCounter/Views/Bird/Edit.cshtml
@model Bird
@{
    ViewData["Title"] = "Edit " + @Model.Name;
}
<form method="post">
    <partial name="CreateEditPartial" model="Model"/>
    <input type="submit" value="Confirm" class="btn btn-primary">
</form>

BirdCounter/Views/Bird/Index.cshtml
@{
    ViewData["Title"] = "Manage birds";
}

<div>
    <h1 class="index__action">Manage birds</h1>
    <a asp-action="Add" class="btn-primary index__action">Add new bird</a>
</div>
<h2 class="index__action">Bird Catalog</h2>
<div class="bird__list--wrapper">
    @foreach (Bird bird in Model.Birds)
    {
        <partial name="BirdPartial" model="bird"/>
    }
</div>

BirdCounter/Views/Home/BirdPartial.cshtml
@model BirdCounter.Models.Bird;

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Url.Content(Model.Image)" alt="Card image cap" runat="server">
    <div class="card-body">
        <h2 class="card-title">@Model.Name</h2>
        <p class="card-text">@Model.Description</p>
    </div>
</div>

BirdCounter/Views/Home/Count.cshtml
@{
    ViewData["Title"] = "New Session";
}
@using System.ComponentModel
@model BirdCounter.Controllers.HomeController


<h1>Current Session</h1>
<div class="header__wrapper">
    <p class="session__header">Session started at: @Model.CurrentCount.session.StartTime</p>
    <a asp-action="EndSession" asp-route-id="@Model.CurrentCount.session.Id" class="btn-danger session__end">
        End session
    </a>
</div>


<table class="table table-striped table__sessions">
    <thead>
    <tr>
            <td>
                Bird
            </td>
            <td>
                no. of spottings
            </td>
            <td>
                actions
            </td>
    </tr>
    </thead>
    <tbody>
    @foreach (BirdSession bs in Model.CurrentCount.birds)
    {
        <tr>
            <td>
                @bs.bird.Name
            </td>
            <td>
                @bs.count.Count
            </td>
            <td>
                <a asp-action="AddCount" asp-route-sessionId="@Model.CurrentCount.session.Id" asp-route-birdId="@bs.bird.Id">+</a>
                <a asp-action="SubtractCount" asp-route-sessionId="@Model.CurrentCount.session.Id" asp-route-birdId="@bs.bird.Id">-</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<h1>Bird Catalog</h1>
<div class="bird__list--wrapper">
    @foreach (Bird b in Model.Birds)
    {
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="@Url.Content(b.Image)" alt="Card image cap" runat="server">
            <div class="card-body">
                <h2 class="card-title">@b.Name</h2>
                <p class="card-text">@b.Description</p>
                <div class="buttons__wrapper">
                    <a asp-action="AddCount" class="add__bird" asp-route-BirdId="@b.Id" asp-route-sessionId="@Model.CurrentCount.session.Id" >+</a>
                </div>
            </div>
        </div>
    }
</div>

BirdCounter/Views/Home/CountPartial.cshtml
@model BirdCounter.Models.BirdSession

BirdCounter/Views/Home/Detail.cshtml
@model BirdCounter.Models.DetailObject

<h1>
    Session no. @Model.session.Id
</h1>
<div class="times__wrapper">
    <p>Start time: @Model.session.StartTime</p>
    <p>End time: @Model.session.EndTime</p>
</div>
<h2>Birds counted: </h2>
<table class="table table-striped">
    <thead>
    <td>
        species
    </td>
    <td>
        no. of spottings
    </td>
    </thead>
    <tbody>
    @foreach (BirdSession c in Model.birds)
    {
        <partial name="DetailPartial" model="c"/>
    }
    </tbody>
</table>

BirdCounter/Views/Home/DetailPartial.cshtml
@model BirdCounter.Models.BirdSession
<tr>
    <td>@Model.bird.Name</td>
    <td>@Model.count.Count</td>
</tr>

BirdCounter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1 class="document__title main__title">Sessions</h1>
<a asp-action="Count" class="btn-primary start__btn">
    Start new session
</a>
<table class="table table-striped table__sessions">
    <thead>
    <tr>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Actions</td>
    </tr>
    </thead>
    <tbody>
        @foreach (Session s in Model.Sessions)
        {
            <partial name="RowPartial" model="s"/>
        }
    </tbody>
</table>

BirdCounter/Views/Home/RowPartial.cshtml
@model BirdCounter.Models.Session

<tr>
    <td>@Model.StartTime</td>
    <td>@Model.EndTime</td>
    <td>
        <a class="btn-link" asp-action="Detail" asp-route-id="@Model.Id">Detail</a>
    </td>
</tr>

BirdCounter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BirdCounter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BirdCounter</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Bird" asp-action="Index">Manage Birds</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - BirdCounter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>